#pragma once

#define redCreateProcedureComputingLanguage_np_count_13
#define _np1_redCreateProcedureComputingLanguage context
#define _np2_redCreateProcedureComputingLanguage gpu
#define _np3_redCreateProcedureComputingLanguage handleName
#define _np4_redCreateProcedureComputingLanguage procedureCache
#define _np5_redCreateProcedureComputingLanguage procedureParameters
#define _np6_redCreateProcedureComputingLanguage gpuCodeMainProcedureName
#define _np7_redCreateProcedureComputingLanguage gpuCode
#define _np8_redCreateProcedureComputingLanguage stateExtension
#define _np9_redCreateProcedureComputingLanguage outProcedure
#define _np10_redCreateProcedureComputingLanguage outStatuses
#define _np11_redCreateProcedureComputingLanguage optionalFile
#define _np12_redCreateProcedureComputingLanguage optionalLine
#define _np13_redCreateProcedureComputingLanguage optionalUserData

